# NumPy Array

### Convert python list to NumPy array

In [1]:
my_list = [1, 2, 3]

In [3]:
type(my_list)

list

In [4]:
import numpy as np

In [6]:
nparr = np.array(my_list)

In [7]:
type(nparr)

numpy.ndarray

In [8]:
my_2d_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
type(my_2d_list)

list

In [10]:
np.array(my_2d_list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### arange Function

In [11]:
np.arange(0, 11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

**Even Numbers**

In [12]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

### zeros Function

In [13]:
np.zeros(3)

array([0., 0., 0.])

**Tuples**

In [15]:
arr = np.zeros((5, 5))

(rows, columns)

In [18]:
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
type(arr)

numpy.ndarray

### ones Function

In [20]:
np.ones(3)

array([1., 1., 1.])

In [21]:
np.ones((2, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### Evenly spaced array elements

In [23]:
np.linspace(0, 5, 10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

### Identity Matrix

In [24]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Random numbers from 0 to 1

In [25]:
np.random.rand(5)

array([0.48462722, 0.32161591, 0.19491169, 0.08028361, 0.59426153])

**Standard Distribution**

In [27]:
np.random.randn(4)

array([-1.38566755,  0.28060093,  0.33812034,  0.6368996 ])

In [28]:
np.random.randn(3, 4)

array([[ 0.86805141, -1.0202464 , -0.78089203,  1.70436043],
       [ 0.57645098,  0.807054  ,  1.48086584,  1.53533781],
       [ 0.33331697, -0.31549187, -0.10399332,  1.41628127]])

### Random Integer 

In [29]:
np.random.randint(1, 100)

99

In [30]:
np.random.randint(1, 100, 10)

array([43, 84, 57, 51, 44, 57, 43, 35, 52, 94], dtype=int32)

### Reshape

In [35]:
arr.reshape(5, 5)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### Max and Min between elements

In [38]:
arr.max()

np.float64(0.0)

In [39]:
arr.min()

np.float64(0.0)

In [40]:
arr.argmax()

np.int64(0)

In [41]:
arr.argmin()

np.int64(0)

In [43]:
arr.shape

(5, 5)

In [46]:
arr.reshape(4, 4)

ValueError: cannot reshape array of size 25 into shape (4,4)

In [48]:
arr.dtype

dtype('float64')

In [49]:
from numpy.random import randint

In [51]:
randint(2, 10)

6